//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// ------------------- Function Prototypes --------------------

void __do_global_ctors(void);
void __main(void);
int64_t _decode_pointer(int64_t result);
int64_t _encode_pointer(int64_t result);
int64_t analyze(char * a1, int64_t a2);
int32_t (*mingw_onexit(int32_t (*func)()))();

// --------------------- Global Variables ---------------------

void (**__onexitbegin)() = NULL; // 0x407970
void (**__onexitend)() = NULL; // 0x407978
int32_t g1 = -1; // 0x402e60
int64_t g2 = 0x63cc6f6861e87bd6; // 0x403020
int32_t initialized = 0; // 0x407030

// ------------------------ Functions -------------------------

// Address range: 0x401560 - 0x4015d7
int64_t analyze(char * a1, int64_t a2) {
    int64_t v1 = 0x100000000 * a2 / 0x100000000 + (int64_t)a1;
    unsigned char v2 = *(char *)v1; // 0x401578
    char v3 = *(char *)(v1 + 2); // 0x401593
    char v4 = *(char *)(v1 + 4); // 0x4015b0
    char v5 = *(char *)(v1 + 6); // 0x4015cb
    return 0x20000 * (int64_t)v3 + 0x1000000 * (int64_t)v2 + 256 * (int64_t)v4 + 2 * (int64_t)v5 & 0xfffffffe;
}

// Address range: 0x4015d7 - 0x4016cb
int main(int argc, char ** argv) {
    // 0x4015d7
    __main();
    puts("Welcome to the superior rev challenge compiled for the superior operating system!");
    puts("What's the superior flag for this superior rev challenge?");
    fgets("actf{ok4y_m4yb3_linux_is_s7ill_b3tt3r}", 128, (struct _IO_FILE *)__iob_func());
    int32_t len = strlen("actf{ok4y_m4yb3_linux_is_s7ill_b3tt3r}"); // 0x401620
    *(char *)((int64_t)(len - 1) + (int64_t)"actf{ok4y_m4yb3_linux_is_s7ill_b3tt3r}") = 0;
    int32_t v1 = 0; // 0x401640
    if (len != 39) {
        // 0x401642
        puts("Your flag is way too different from my superior flag!");
        exit(1);
        // UNREACHABLE
    }
    int64_t v2 = analyze("actf{ok4y_m4yb3_linux_is_s7ill_b3tt3r}", (int64_t)v1); // 0x40166d
    int32_t v3 = *(int32_t *)(int64_t)&g2; // 0x401688
    while (v3 == (int32_t)v2) {
        // 0x4016a9
        v1++;
        if (v1 >= 32) {
            // 0x4016b4
            puts("Oh wow a fellow windows user!");
            return 0;
        }
        v2 = analyze("actf{ok4y_m4yb3_linux_is_s7ill_b3tt3r}", (int64_t)v1);
        v3 = *(int32_t *)(4 * (int64_t)v1 + (int64_t)&g2);
    }
    // 0x40168f
    puts("Maybe if you spent more time using the superior operating system you would actually get the flag.");
    exit(1);
    // UNREACHABLE
}

// From module:   ./mingw-w64-crt/crt/atonexit.c
// Address range: 0x4016d0 - 0x40177d
// Line range:    33 - 53
int32_t (*mingw_onexit(int32_t (*func)()))() {
    int64_t v1 = _decode_pointer((int64_t)__onexitbegin); // 0x4016df
    void (**onexitend)() = (void (**)())v1; // bp-24, 0x4016e8
    if (v1 == -1) {
        // 0x401765
        return _onexit(func);
    }
    // 0x4016ef
    _lock(8);
    onexitend = (void (**)())_decode_pointer((int64_t)__onexitbegin);
    int64_t v2 = _decode_pointer((int64_t)__onexitend); // bp-16, 0x401723
    int32_t (*result)() = __dllonexit(func, &onexitend, (void (***)())&v2); // 0x401728
    int64_t v3 = _encode_pointer((int64_t)onexitend); // 0x401735
    *(int64_t *)&__onexitbegin = v3;
    int64_t v4 = _encode_pointer(v2); // 0x401746
    *(int64_t *)&__onexitend = v4;
    _unlock(8);
    return result;
}

// From module:   ./mingw-w64-crt/crt/gccmain.c
// Address range: 0x4017e0 - 0x401846
// Line range:    32 - 39
void __do_global_ctors(void) {
    int64_t v1 = 0;
    int64_t v2 = v1 + 1 & 0xffffffff; // 0x401836
    while (*(int64_t *)(8 * v2 + (int64_t)&g1) != 0) {
        // 0x401836
        v1 = v2;
        v2 = v1 + 1 & 0xffffffff;
    }
    if (v1 == 0) {
        // 0x40181b
        atexit((void (*)())0x4017a0);
        return;
    }
    int64_t v3 = 8 * (v1 - (v1 + 0xffffffff & 0xffffffff)) + (int64_t)&g1 - 8; // 0x401807
    int64_t v4 = 8 * v1 + (int64_t)&g1; // 0x40180c
    while (v4 - 8 != v3) {
        // 0x401810
        v4 -= 8;
    }
    // 0x40181b
    atexit((void (*)())0x4017a0);
}

// From module:   ./mingw-w64-crt/crt/gccmain.c
// Address range: 0x401850 - 0x40186f
// Line range:    53 - 58
void __main(void) {
    // 0x401850
    if (initialized != 0) {
        // 0x40185a
        return;
    }
    // 0x401860
    initialized = 1;
    __do_global_ctors();
}

// Address range: 0x401c80 - 0x401c84
int64_t _decode_pointer(int64_t result) {
    // 0x401c80
    return result;
}

// Address range: 0x401c90 - 0x401c94
int64_t _encode_pointer(int64_t result) {
    // 0x401c90
    return result;
}

// --------------- Statically Linked Functions ----------------

// int32_t atexit(void (*a1)());

// --------------- Dynamically Linked Functions ---------------

// _onexit_t __dllonexit(_onexit_t func, _PVFV ** pbegin, _PVFV ** pend);
// int64_t __iob_func(void);
// void __cdecl _lock(int locknum);
// _onexit_t _onexit(_onexit_t Function);
// void __cdecl _unlock(int locknum);
// void exit(int status);
// char * fgets(char * restrict s, int n, FILE * restrict stream);
// int puts(const char * s);
// size_t strlen(const char * s);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (6.3.0)
// Detected language: C
// Detected functions: 7
