//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// ------------------- Function Prototypes --------------------

int64_t print_flag(void);

// --------------------- Global Variables ---------------------

struct _IO_FILE * g1 = NULL; // 0x601080
int32_t g2;

// ------------------------ Functions -------------------------

// Address range: 0x4007e7 - 0x4008ae
int64_t print_flag(void) {
    int64_t v1 = __readfsqword(40); // 0x4007f2
    int32_t v2 = getegid(); // 0x400801
    setresgid(v2, v2, v2);
    struct _IO_FILE * file = fopen("flag.txt", "r"); // 0x400835
    if (file == NULL) {
        // 0x40084b
        puts("Cannot read flag file.");
        exit(1);
        // UNREACHABLE
    }
    // 0x400861
    int64_t str; // bp-152, 0x4007e7
    fgets((char *)&str, 128, file);
    printf("%s", &str);
    int64_t result = 0; // 0x4008a5
    if (v1 != __readfsqword(40)) {
        // 0x4008a7
        __stack_chk_fail();
        result = &g2;
    }
    // 0x4008ac
    return result;
}

// Address range: 0x4008ae - 0x400a25
int main(int argc, char ** argv) {
    int64_t v1 = __readfsqword(40); // 0x4008c6
    puts("Congratulations on running the binary!");
    puts("Now there are a few more things to tend to.");
    puts("Please type \"give flag\" (without the quotes).");
    int64_t str; // bp-152, 0x4008ae
    fgets((char *)&str, 128, g1);
    char * found_char_pos = strchr((char *)&str, 10); // 0x400923
    if (found_char_pos != NULL) {
        // 0x400939
        *found_char_pos = 0;
    }
    // 0x400943
    int64_t v2; // 0x4008ae
    if (strcmp((char *)&str, "give flag") == 0) {
        // 0x400982
        puts("Good job!");
        if ((int32_t)argc > 1) {
            int64_t * str2 = (int64_t *)((int64_t)argv + 8); // 0x4009b5
            if (strcmp((char *)*str2, "banana") == 0) {
                // 0x4009f4
                puts("Well I think it's about time you got the flag!");
                print_flag();
                v2 = 0;
            } else {
                // 0x4009cb
                printf("You provided \"%s\", not \"banana\". Please try again.\n", (char *)*str2);
                v2 = 1;
            }
        } else {
            // 0x400997
            puts("Now run the program with a command line argument of \"banana\" and you'll be done!");
            v2 = 1;
        }
    } else {
        // 0x40095d
        printf("You entered \"%s\", not \"give flag\". Please try again.\n", &str);
        v2 = 1;
    }
    int64_t result = v2; // 0x400a1c
    if (v1 != __readfsqword(40)) {
        // 0x400a1e
        __stack_chk_fail();
        result = &g2;
    }
    // 0x400a23
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// void __stack_chk_fail(void);
// void exit(int status);
// char * fgets(char * restrict s, int n, FILE * restrict stream);
// FILE * fopen(const char * restrict filename, const char * restrict modes);
// __gid_t getegid(void);
// int printf(const char * restrict format, ...);
// int puts(const char * s);
// int setresgid(__gid_t rgid, __gid_t egid, __gid_t sgid);
// char * strchr(char * s, int c);
// int strcmp(const char * s1, const char * s2);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (7.4.0)
// Detected functions: 2
